dwa_ackermann_node:
  ros__parameters:
    # Frames
    base_link: "ego_racecar/base_link"
    map_frame: "map"

    # Topics
    scan_topic: "/scan"
    odom_topic: "/ego_racecar/odom"
    lookahead_sub_topic: "lookahead_goal"
    goal_topic: "/goal_pose"
    drive_topic: "/drive"
    goal_marker_topic: "goal_marker"
    horizon_marker_topic: "dwa_horizons"

    # General parameters
    laser_distance_from_base_link: 0.275
    wheel_base_length: 0.33

    # DWA params
    dwa:
      n_v_omega_max: 25
      n_v_omega_min: 12
      prediction_horizon: 8
      omega_max_full: 2.0 # FULL omega window (low speed)
      omega_max_min: 1.0 # MINIMUM omega window (high speed)
      v_min: 0.5
      v_max: 5.5
      integ_vel_scale: 5.8
      integ_vel_scale_offset: 1.0
      dt: 0.2
      r_buffer: 0.1
      obstacles_cost: 0.02
      max_vel_cost: 2.0
      min_vel_cost: 1.0
      limit_angle: 120
      max_lidar_distance: 4.5
      min_lidar_distance: 0.05
      spread_gaussian: 2.0 # For computing linear velocities for each omega
      kp: 1.8
      kd: 1.5